server:
  port: 8081

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296